# make sure you use skhd, otherwise forget about "ł"
config-version = 2

after-startup-command = []

start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = []
on-focus-changed = []

automatically-unhide-macos-hidden-apps = false

# get app id: lsappinfo | rg "bundleID|ASCII name"

[[on-window-detected]]
   if.app-id = "org.keepassxc.keepassxc"
   run = "layout floating"

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 3
    inner.vertical =   3
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    cmd-shift-f = 'fullscreen'
    cmd-shift-h = 'resize width -50'
    cmd-shift-j = 'resize height +50'
    cmd-shift-k = 'resize height -50'
    cmd-shift-l = 'resize width +50'
    cmd-shift-e = 'balance-sizes'
    cmd-shift-n = 'flatten-workspace-tree'

    alt-tab = 'workspace-back-and-forth'
