# make sure you use skhd, otherwise forget about "ł"
config-version = 2

after-startup-command = []

start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = []
on-focus-changed = []

automatically-unhide-macos-hidden-apps = false

# get app id: lsappinfo | rg "bundleID|ASCII name"

[[on-window-detected]]
   if.app-id = "org.keepassxc.keepassxc"
   run = "layout floating"

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 3
    inner.vertical =   3
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0
