#!/usr/bin/env bash

command=$1

case $command in 

  vim )
    cd scripts
    ./vim
    ;;

  shutter )
    cd scripts
    ./shutter
    ;;

  apt )
    cd scripts
    ./ubuntuapt
    ;;

  unity )
    cd scripts
    ./gsettingsunity
    ;;

  * )
    echo "options: vim|shutter|apt"
    ;;
esac

