#!/usr/bin/env bash

set -eo pipefail
# -----------------------------------------------------------------------------
# Global variables
# -----------------------------------------------------------------------------

CONFIGS=stow

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _remove_default_dotfiles {
  echo '[*] Removing default ~/ configurations ...'
  files=$(ls -a $CONFIGS)
  for location in $files; do
    [[ "$location" != "." && "$location" != ".." && "$location" != ".config" ]] && rm -rf ~/"$location"
  done

  echo '[*] Removing default ~/.config configurations ...'
  files=$(ls -a $CONFIGS/.config)
  for location in $files; do
    [[ "$location" != "." && "$location" != ".." ]] && rm -rf "$HOME/.config/$location"
  done
}

# -----------------------------------------------------------------------------
# Define your tasks below
# -----------------------------------------------------------------------------

function dotfiles { # Purge configs and reinstall dotfiles
  echo -e "\033[1;31mLAST CHANCE!\033[0m"
  echo "your spotlight_commands will be deleted"
  echo "<ctrl>+c to cancel this operation"
  echo "or type AGREE to continue"
  read -r agree
  if [ "$agree" == "AGREE" ]; then
    _remove_default_dotfiles
    restow
  else
    echo "Aborting..."
  fi
}

function restow { # Update dotfiles
  echo '[*] Installing/updating dot files...'
  stow -Rt ~ $CONFIGS
}

function apps { # Install brew casks and formulas
  ./osx/apps
  ./osx/start-apps
}

function defaults { # Set sensible macos defaults
  ./osx/defaults
}

function fonts { # Install fonts
  cp ./fonts/source-code-pro/*.ttf /Library/Fonts/
}

function neovim { # Install neovim tools
  ./osx/nvim
}

function stop-processes { # Stop or `install stop-processes --unload` processes
  ./osx/stop-processes "$@"
}

function fresh { # Do everything at once. Please run this only once ;)
  defaults
  dotfiles
  fonts
  neovim
  stop-processes --unload
  apps
}

# -----------------------------------------------------------------------------

function help { # Display this helpful help information
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  functions=$(compgen -A function | grep -v "^_")
  display=""

  for f in $functions; do
    display+="  $f#"
    display+=$(grep "function $f .*" "${0}" | awk -F '#' '{print $NF}')
    display+=$'\n'
  done

  echo "$display" | column -t -s "#"
}

"${@:-help}"
