#!/usr/bin/env bash

set -eo pipefail
# -----------------------------------------------------------------------------
# Global variables
# -----------------------------------------------------------------------------

CONFIGS=stow

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _remove_default_dotfiles {
    echo '[*] Removing default ~/ configurations ...'
    files=$(ls -a $CONFIGS)
    for location in $files
    do
        [[ "$location" != "." && "$location" != ".." && "$location" != ".config" ]] && rm -rf ~/"$location"
    done

    echo '[*] Removing default ~/.config configurations ...'
    files=$(ls -a $CONFIGS/.config)
    for location in $files
    do
        [[ "$location" != "." && "$location" != ".." ]] && rm -rf "$HOME/.config/$location"
    done
}

function _stow_install_dotfiles {
    echo '[*] Installing our dotfiles ...'
    stow -Rt ~ $CONFIGS
}

function _install_lsp {
    wget -O /tmp/marksman https://github.com/artempyanykh/marksman/releases/download/2022-06-23/marksman-macos && mv /tmp/marksman /usr/local/bin/marksman && chmod +x /usr/local/bin/marksman
    npm i -g bash-language-server
    npm i -g pyright
}

# -----------------------------------------------------------------------------

function cmd {
    # run any command
    exec "${@}"
}

function install_dotfiles {
    # remove existing files, and install our dotfiles
    _remove_default_dotfiles
    _stow_install_dotfiles
}

function fresh {
    ## for a fresh MACOS installation, intall all the things!

    ./scripts/osx.install-brew
    install_dotfiles
    ./scripts/osx.set-defaults
    cp ./fonts/source-code-pro/*.ttf /Library/Fonts/
    _install_lsp
}

function help {
    printf "%s <task> [args]\n\nTasks:\n" "${0}"

    compgen -A function | grep -v "^_" | cat -n

    printf "\nExtended help:\n  Each task has comments for general usage\n"
}

"${@:-help}"
