#!/usr/bin/env sh

limelight -m config width	2
limelight -m config radius	8
limelight -m config placement	interior
limelight -m config active_color	0xff296cf8
limelight -m config normal_color	0x00ffffff

echo "limelight configuration loaded.."
