#!/usr/bin/env bash

bg="#2D3441"
export FZF_DEFAULT_OPTS="
--inline-info
--prompt='►▶ '
--pointer='► '
--bind=ctrl-space:toggle+up,ctrl-d:half-page-down,ctrl-u:half-page-up
--bind=alt-v:toggle-preview,alt-j:preview-down,alt-k:preview-up
--bind=alt-d:preview-half-page-down,alt-u:preview-half-page-up
--preview-window 'border-sharp'
--color=\"gutter:$bg,bg+:$bg,bg:$bg,fg:#ffb000,fg+:italic,fg+:#ffb000,hl:#689d6a,hl+:#ffffff,hl+:underline,hl+:italic,border:#ffb000\"
"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
