#!/usr/bin/env bash

# History settings (don't save lines beginning with space or matching the
# previous entry)
export HISTCONTROL=ignoreboth
export HISTSIZE=100000
export HISTFILESIZE=200000
export HISTIGNORE="ls:cd -"
export HISTFILE=${XDG_DATA_HOME}/bash/.bash_history
if [ ! -d "${XDG_DATA_HOME}/bash/" ]; then
  mkdir -p "${XDG_DATA_HOME}/bash/"
fi
shopt -s histappend # append to history i.e don't overwrite it

# Save multiline commands in same history entry with embedded newlines
shopt -s cmdhist
shopt -s lithist
