#!/usr/bin/env bash

source "$HOME/.config/bash/xdg"
source "$HOME/.config/bash/colors"
source "$HOME/.config/bash/path"
source "$HOME/.config/bash/settings"
source "$HOME/.config/bash/functions"
source "$HOME/.config/bash/aliases"
source "$HOME/.config/bash/history"
source "$HOME/.config/bash/fzf_config"
source "$HOME/.config/bash/fzf_history"
source "$HOME/.config/bash/prompt"
## APPS
source "$HOME/.config/bash/z"
source "$HOME/.config/bash/lynx"
