#!/usr/bin/env bash

PS1=""
# current time
PS1+="\[${gray}\]\t"
# last command exit status
PS1+=' $(s=$?; [ $s == 0 ] && echo "\[${gray}\]${s}" || echo "\[${red}\]${s}")'
# working directory full path
PS1+=" \[${green}\]\w"
PS1+="\[${yellow}\]\$(git_branch_read -wp)\[${reset}\]"
PS1+=" \[${white}\]\$ \[${reset}\]" 
export PS1
