#!/usr/bin/env bash

PS1=''
PS1+='\[${white}\]\t' # current time
PS1+=' $(s=$?; [ $s == 0 ] && echo "${reset}${s}" || echo "${red}${s}") ' # last command exit status
PS1+="\[\033]0;\W\007\]"; # working directory base name
#PS1+="\[${white}\]:: ";
PS1+="\[${green}\]\w"; # working directory full path
PS1+="\[${yellow}\]\$(git_branch_read -wp)\[${reset}\]";
PS1+=" \[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
export PS1;
