#!/usr/bin/env bash

function pgb {
  # make a copy of the previous exit status
  local _ps=$?
  git rev-parse --abbrev-ref HEAD 2>/dev/null | sed -e 's/\(.*\)/ <\1>/'
  # and return it so the redness can start
  return $_ps
}

PS1=""
# current time
PS1+="\[${gray}\]\t"
# working directory full path
PS1+=" \[${green}\]\w"
# git branch
PS1+="\[${yellow}\]\$(pgb)\[${reset}\]"
# the dollar will be red if exit code was baaaad
PS1+=' $([ $? == 0 ] && echo "\[${white}\]\$ " || echo "\[${red}\]\$ ")'
PS1+="\[${reset}\]"

export PS1
