#!/usr/bin/env bash

set -euo pipefail

dir=$(dirname "$0")
readonly dir
readonly result="$dir/bashrc"
declare -a firstfiles=(_top _vars xdg path)

is_firstfile() {
  for i in "${firstfiles[@]}"; do
    [[ $i == "$1" ]] && return 0
  done
  return 1
}

: > "$result"

append() {
  {
    echo ""
    echo "# ----- $1"
    echo ""
    cat "$1"
  } >> "$result"
}

for f in "${firstfiles[@]}"; do
  append "$dir/src/$f"
done

main() {
  while IFS= read -r file; do
    local fn=${file:6}
    is_firstfile "$fn" && continue
    append "$file"
  done < <(ls "$dir"/src/*)
}

main "$@"
