#!/usr/bin/env bash

# Hide the deprecation warning (zsh) macos
export BASH_SILENCE_DEPRECATION_WARNING=1

PATH="${PATH}:${HOME}/bin:${HOME}/.cargo/bin:${HOME}/.local/bin:/opt/homebrew/bin"
PATH="/usr/local/sbin:$PATH"

export VISUAL=nvim
export EDITOR="$VISUAL"
export SYSTEMD_EDITOR="$VISUAL"
# shellcheck disable=2155
export SHELL="$(brew --prefix)/bin/bash"

# todo: these exports probably should be placed in another file
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME"/python
export PYTHONUSERBASE="$XDG_DATA_HOME"/python
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
alias wget="wget --hsts-file='$XDG_CACHE_HOME'/wget-hsts"
# dangerous - first move your existing passwords,
# see supported apps https://wiki.archlinux.org/title/XDG_Base_Directory
#export GNUPGHOME="$XDG_DATA_HOME"/gnupg,
#export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass

# Highlight section titles in manual pages.
# shellcheck disable=2154
export LESS_TERMCAP_md="$yellow"
