#!/usr/bin/env bash

# Hide the deprecation warning (zsh) macos
export BASH_SILENCE_DEPRECATION_WARNING=1

PATH="${PATH}:${HOME}/bin:${HOME}/bin/dotfiles"
PATH="${PATH}:${HOME}/.cargo/bin"
export VISUAL=nvim
export EDITOR="$VISUAL"

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";
