#!/usr/bin/env bash

# Hide the deprecation warning (zsh) macos
export BASH_SILENCE_DEPRECATION_WARNING=1

PATH="${PATH}:${HOME}/bin:${HOME}/bin/dotfiles:${HOME}/.cargo/bin"
export VISUAL=nvim
export EDITOR="$VISUAL"
export SYSTEMD_EDITOR="$VISUAL"


# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";
