#!/usr/bin/env bash

. ./_utils.sh

inform_about_sudo

say "injecting apt-repo ... "
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
say_done

_=`grep -q "download.docker.com/linux/ubuntu" /etc/apt/sources.list`
if [ $? != 0 ]; then
  say "Injecting Docker apt-repo ... "
  echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee --append /etc/apt/sources.list
fi

sudo apt install -y docker-ce

_=$(command -v docker-compose)
if [ "$?" != 0 ]; then
  say "Installing docker-compose ... "
  curl -sL https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  say_done
fi

inform "Happy DOCKERing"
