require "defaults.settings"
require "defaults.keymaps"
require "defaults.plugins"
require "defaults.telescope"
require "defaults.treesitter"
require "defaults.colorscheme"
require "defaults.lsp"
require "defaults.lsp.null-ls"
