#!/usr/bin/env bash
# shellcheck disable=2034

if tput setaf 1 &> /dev/null; then
    tput sgr0; # reset colors
    bold=$(tput bold);
    reset=$(tput sgr0);
    black=$(tput setaf 0);
    blue=$(tput setaf 153);
    cyan=$(tput setaf 37);
    green=$(tput setaf 64);
    orange=$(tput setaf 166);
    purple=$(tput setaf 125);
    red=$(tput setaf 9);
    violet=$(tput setaf 61);
    white=$(tput setaf 15);
    yellow=$(tput setaf 136);
    gray=$(tput setaf 240);
else
    bold='';
    reset="\e[0m";
    black="\e[1;30m";
    blue="\e[1;34m";
    cyan="\e[1;36m";
    green="\e[1;32m";
    orange="\e[1;33m";
    purple="\e[1;35m";
    red="\e[1;31m";
    violet="\e[1;35m";
    white="\e[1;37m";
    yellow="\e[1;33m";
    gray="\e[1;33m";
fi

function sayok {
  echo -e " [\033[32m√\033[m] $1"
}

function sayfail {
  echo -e " [\033[37m✗\033[0m] $1"
}

function sayask {
  echo -e " [\033[34m?\033[m] $1"
}

function saybox {
  local text="$1"
  local len=${#text}
  len=$((len + 8))
  local hl
  hl=$(printf "+"; printf '=%.0s' $(seq 1 "$len"); printf "+")
  echo ""
  # top line
  echo "$hl"
  #content line
  echo "|    ${cyan}$text${reset}    |"
  #bottom line
  echo "$hl"
}
