#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/../stow/bin/.lib
. "$(dirname "$0")"/install-brew

ebox "Installing tools"

# todo: reimplement with brew bundle
# brew bundle dump --force --all --verbose
# brew bundle --verbose --file $(pwd)/Brewfile

brew install \
  ack \
  bash \
  curl \
  expect \
  fzf \
  git \
  git-delta \
  gnupg \
  htop \
  jq \
  koekeishiya/formulae/skhd \
  koekeishiya/formulae/yabai \
  lazygit \
  less \
  ncdu \
  neovim \
  node \
  osx-cpu-temp \
  pass \
  rg \
  rust \
  shellharden \
  stow \
  tldr \
  tmux \
  tree \
  vim \
  watch \
  wget \
  yarn \
  z

ebox "Installing casks"

brew install --cask --no-quarantine \
  alacritty \
  brave-browser \
  caffeine \
  itsycal \
  firefox \
  hammerspoon \
  keepassxc \
  keycastr \
  losslesscut \
  lulu \
  openoffice \
  shottr \
  slack \
  sublime-text \
  vlc \
  xbar

ebox "Cleanup"
brew cleanup
