#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/_functions

saybox "Let's go!"

_COMPUTER_NAME=$(scutil --get ComputerName)
echo -n "Set computer name [$_COMPUTER_NAME]: "
read -r COMPUTER_NAME

if [ "$COMPUTER_NAME" = "" ]; then
  COMPUTER_NAME=$_COMPUTER_NAME
fi

# --------------------------------------------------
saybox "Prepare env"

sayok "Close preferences window"
osascript -e 'tell application "System Preferences" to quit'

# --------------------------------------------------
saybox "Set ComputerName"

sudo scutil --set ComputerName "$COMPUTER_NAME"
sudo scutil --set HostName "$COMPUTER_NAME"
sudo scutil --set LocalHostName "$COMPUTER_NAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$COMPUTER_NAME"
sayok "Set computer name (as done via System Preferences → Sharing)"

# --------------------------------------------------
saybox "Tools and Look"

chsh -s /bin/bash
sayok "bash is better than ZSH"

defaults write NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"
sayok "Set highlight color to green"

# --------------------------------------------------
saybox "Top bar"

launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2>/dev/null
sayok "Disable Notification Center and remove the menu bar icon"

defaults write com.apple.menuextra.battery ShowPercent -string 'YES'
sayok "Show battery percentage"

defaults write NSGlobalDomain NSToolbarTitleViewRolloverDelay -float 0
sayok "Adjust toolbar title rollover delay"

# --------------------------------------------------
saybox "Finder"

defaults write com.apple.finder WarnOnEmptyTrash -bool false
sayok "Trash: disable warning on empty"

defaults write com.apple.finder _FXSortFoldersFirst -bool true
sayok "Keep folders on top when sorting by name"

defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
sayok "When performing a search, search the current folder by default"

defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder NewWindowTarget -string PfHm
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
defaults write com.apple.finder QuitMenuItem -bool true
sayok "Finder fine tuning"

defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
sayok "Disable the warning when changing a file extension"

defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
sayok "Disable opening and closing window animations"

defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
sayok "Expand save panel by default"

defaults write com.apple.finder DisableAllAnimations -bool true
sayok "Finder: disable window animations and Get Info animations"

# --------------------------------------------------
saybox "Audio"

sudo nvram SystemAudioVolume=" "
sudo nvram StartupMute=%01
sayok "Disable startup sound"

defaults write com.apple.sound.beep.feedback -bool false
sayok "Disable audio feedback when volume is changed"

defaults write "Apple Global Domain" "com.apple.sound.beep.volume" -float 0
sayok "Disable audio feedback beeps"

defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
sayok "Increase sound quality for Bluetooth headphones/headsets"

# --------------------------------------------------
saybox "Keyboard"

defaults write -g KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 15
sayok "Keyboard: fast repeat"

defaults write -g ApplePressAndHoldEnabled -bool false
sayok "Keyboard: disable letter popup on hold"

defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
sayok "Disable press-and-hold for keys in favor of key repeat"

defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
sayok "Disable smart quotes and dashes as they’re annoying when typing code"
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false
sayok "Disable auto-correct"

defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
sayok "Enable full keyboard access for all controls"

launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2>/dev/null
sayok "Stop iTunes from responding to the keyboard media keys"

# --------------------------------------------------
saybox "Trackpad"

defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true
sayok "Trackpad: disable Fore Click haptic feedback"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad DragLock -bool false
defaults write com.apple.AppleMultitouchTrackpad DragLock -bool false
sayok "Trackpad: disable DragLock"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Dragging -bool false
defaults write com.apple.AppleMultitouchTrackpad Dragging -bool false
sayok "Trackpad: disable Dragging"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool false
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool false
sayok "Trackpad: three finger drag"

defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
sayok "Trackpad: enable tap to click for this user and for the login screen"

defaults write .GlobalPreferences com.apple.trackpad.scaling 2
sayok "Trackpad: Faster pointer"

defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -int 1
defaults -currentHost write -g com.apple.trackpad.enableSecondaryClick -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 0
defaults write com.apple.AppleMultitouchTrackpad TrackpadCornerSecondaryClick -int 0
defaults -currentHost write -g com.apple.trackpad.trackpadCornerClickBehavior -int 0
sayok "Map 'click or tap with two fingers' to the secondary click"

# --------------------------------------------------
saybox "SecOps"

sayask "Enable FileVault"
sudo fdesetup enable || true
sayok "Enable FileVault"

sayok "Disable captive control"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

sayask "Enable firewall"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on
sayok "Enable firewall"

sayask "Disable time machine"
sudo tmutil disable || true
sayok "Disable time machine"

defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
sayok "Prevent Time Machine from prompting to use new hard drives as backup volume"

defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
sayok "Require password immediately after sleep or screen saver begins"

# --------------------------------------------------
saybox "Photos"

defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
sayok "Prevent Photos from opening automatically when devices are plugged in"

# --------------------------------------------------
saybox "Screen"

sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true
sayok "Enable HiDPI display modes (requires restart)"

sudo defaults write com.apple.universalaccess reduceMotion -bool true
sayok "instead of sliding entire screen left/right, cross-fade... less jarring"

sudo defaults write com.apple.universalaccess reduceTransparency -bool true
sayok "Make menubar always white (and turn off transparency everywhere)"

# --------------------------------------------------
saybox "Dock"

defaults write com.Apple.Dock showLaunchpadGestureEnabled -bool false
sayok "Disable launchpad finger swipes"
defaults write com.Apple.Dock showAppExposeGestureEnabled -bool false
sayok "Disable expose finger swipes"
defaults write com.Apple.Dock show-recents -bool false
sayok "Don't show recently used applications in the Dock"

defaults write com.apple.dock magnification -int 1
defaults write com.apple.dock largesize -int 50
sayok "Dock: magnify"

defaults write com.apple.dock persistent-apps -array
defaults write com.apple.dock persistent-others -array
sayok "Dock: remove all app icons"

defaults write com.apple.dock showhidden -bool true
defaults write com.apple.dock tilesize -int 22
sayok "Dock: hidden icons are transparent and small"

sayok "Dock: position right"
defaults write com.apple.dock orientation -string 'right'

sayok "Do not show app indicators in Dock"
defaults write com.apple.dock show-process-indicators -bool FALSE

# --------------------------------------------------
saybox "In's and Out's"

defaults write -g NSAutomaticCapitalizationEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticTextCompletionEnabled -bool false
sayok "Disable autocorrect and key substitutions"

defaults write com.apple.ActivityMonitor ShowCategory -int 0
sayok "Show all processes in Activity Monitor"

sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "I AM SERIOUS"
sayok "Set login screen welcome text"

sudo defaults write /Library/Preferences/com.apple.alf allowdownloadsignedenabled -bool false || true
sayok "Disable automatic signed software whitelisting"

sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool false || true
sayok "Disable automatic software whitelisting"

sudo defaults write /Library/Preferences/com.apple.loginwindow DisableConsoleAccess -bool true
sayok "Disable console logon from the logon screen"

sudo /usr/libexec/PlistBuddy -c "Set 'AC Power':'Display Sleep Timer' 5" /Library/Preferences/com.apple.PowerManagement.plist
sayok "AC display sleep timer"

sudo /usr/libexec/PlistBuddy -c "Set 'Battery Power':'Display Sleep Timer' 2" /Library/Preferences/com.apple.PowerManagement.plist
sayok "Battery display sleep timer"

defaults write com.apple.dock mru-spaces -bool false
sayok "Don’t automatically rearrange Spaces based on most recent use"

defaults write com.apple.dock wvous-tl-corner -int 0
defaults write com.apple.dock wvous-tr-corner -int 0
defaults write com.apple.dock wvous-bl-corner -int 0
defaults write com.apple.dock wvous-br-corner -int 0
sayok "Disable hot corners"

defaults write com.apple.dock expose-animation-duration -float 0.1
sayok "Speed up Mission Control animations"

defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
sayok "Save to disk (not to iCloud) by default"

defaults write com.apple.CrashReporter DialogType -string "none"
sayok "Disable the crash reporter"

defaults write NSGlobalDomain AppleFontSmoothing -int 2
sayok "Enable subpixel font rendering on non-Apple LCDs"

defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
sayok "Avoid creating .DS_Store files on network or USB volumes"

sudo pmset -a sms 0
sayok "Disable the sudden motion sensor as it’s not useful for SSDs"

defaults write com.apple.AdLib allowApplePersonalizedAdvertising -int 0
sayok "advertising"

# --------------------------------------------------
saybox "Spotlight"

defaults write com.apple.spotlight orderedItems -array \
  '{"enabled" = 1;"name" = "APPLICATIONS";}' \
  '{"enabled" = 1;"name" = "MENU_EXPRESSION";}' \
  '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}' \
  '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
  '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
  '{"enabled" = 0;"name" = "SYSTEM_PREFS";}' \
  '{"enabled" = 0;"name" = "DOCUMENTS";}' \
  '{"enabled" = 0;"name" = "DIRECTORIES";}' \
  '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
  '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
  '{"enabled" = 0;"name" = "PDF";}' \
  '{"enabled" = 0;"name" = "MESSAGES";}' \
  '{"enabled" = 0;"name" = "CONTACT";}' \
  '{"enabled" = 0;"name" = "EVENT_TODO";}' \
  '{"enabled" = 0;"name" = "IMAGES";}' \
  '{"enabled" = 0;"name" = "BOOKMARKS";}' \
  '{"enabled" = 0;"name" = "MUSIC";}' \
  '{"enabled" = 0;"name" = "MOVIES";}' \
  '{"enabled" = 0;"name" = "FONTS";}' \
  '{"enabled" = 0;"name" = "MENU_OTHER";}'
sayok "Disable spotlight bloat"

# Restart spotlight
# --------------------------------------------------
saybox "Finishup, cleanup and restart"

killall "SystemUIServer" >/dev/null 2>&1 || true
sayok "kill: SystemUiServer"
killall "Finder" >/dev/null 2>&1 || true
sayok "kill: Finder"
killall "Dock" >/dev/null 2>&1 || true
sayok "kill: Dock"
killall mds >/dev/null 2>&1 || true
sayok "kill: Spotlight"
# Make sure indexing is enabled for the main volume
sudo mdutil -i on / >/dev/null 2>&1 || true
sayok "revive: Spotlight"
# Rebuild the index from scratch
sudo mdutil -E / >/dev/null 2>&1 || true
sayok "Spotlight - reindex"

# Starting with Mac OS X Mavericks preferences are cached,
# so in order for things to get properly set using `PlistBuddy`,
# the `cfprefsd` process also needs to be killed.
#
# https://github.com/alrra/dotfiles/commit/035dda057ddc6013ba21db3d2c30eeb51ba8f200

killall "cfprefsd" >/dev/null 2>&1 || true
sayok "kill: cached preferences"

saybox "You probably want to restart your machine now...."
sayok "all done!"
