#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/../stow/bin/.lib

ebox "Let's go!"
# --------------------------------------------------

eok "Closing System Preferences window"
osascript -e 'tell application "System Preferences" to quit'

# --------------------------------------------------

_COMPUTER_NAME=$(scutil --get ComputerName)
echo -n "Set computer name [$_COMPUTER_NAME]: "
read -r COMPUTER_NAME

if [ "$COMPUTER_NAME" != "" ] && [ "$COMPUTER_NAME" != "$_COMPUTER_NAME" ]; then
  ebox "Set ComputerName to: $COMPUTER_NAME"
  sudo scutil --set ComputerName "$COMPUTER_NAME"
  sudo scutil --set HostName "$COMPUTER_NAME"
  sudo scutil --set LocalHostName "$COMPUTER_NAME"
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$COMPUTER_NAME"
  eok "Set computer name (as done via System Preferences → Sharing)"
fi

# --------------------------------------------------
ebox "Tools and Look"

defaults write NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"
eok "Set highlight color to green"

# --------------------------------------------------
ebox "Top bar"

launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null
eok "Disable Notification Center and remove the menu bar icon"

defaults write com.apple.menuextra.battery ShowPercent -string 'YES'
eok "Show battery percentage"

defaults write NSGlobalDomain NSToolbarTitleViewRolloverDelay -float 0
eok "Adjust toolbar title rollover delay"

# --------------------------------------------------
ebox "Finder"

defaults write com.apple.finder WarnOnEmptyTrash -bool false
eok "Trash: disable warning on empty"

defaults write com.apple.finder _FXSortFoldersFirst -bool true
eok "Keep folders on top when sorting by name"

defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
eok "When performing a search, search the current folder by default"

defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder NewWindowTarget -string PfHm
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
defaults write com.apple.finder QuitMenuItem -bool true
eok "Finder fine tuning"

defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
eok "Disable the warning when changing a file extension"

defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
eok "Disable opening and closing window animations"

defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
eok "Expand save panel by default"

defaults write com.apple.finder DisableAllAnimations -bool true
eok "Finder: disable window animations and Get Info animations"

# --------------------------------------------------
ebox "Audio"

sudo nvram SystemAudioVolume=" "
sudo nvram StartupMute=%01
eok "Disable startup sound"

defaults write com.apple.sound.beep.feedback -bool false
eok "Disable audio feedback when volume is changed"

defaults write "Apple Global Domain" "com.apple.sound.beep.volume" -float 0
eok "Disable audio feedback beeps"

defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
eok "Increase sound quality for Bluetooth headphones/headsets"

# --------------------------------------------------
ebox "Keyboard"

defaults write -g KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 15
eok "Keyboard: fast repeat"

defaults write -g ApplePressAndHoldEnabled -bool false
eok "Keyboard: disable letter popup on hold"

defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
eok "Disable press-and-hold for keys in favor of key repeat"

defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
eok "Disable smart quotes and dashes as they’re annoying when typing code"
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false
eok "Disable auto-correct"

defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
eok "Enable full keyboard access for all controls"

launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null
eok "Stop iTunes from responding to the keyboard media keys"

# --------------------------------------------------
ebox "Trackpad"

defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true
eok "Trackpad: disable Fore Click haptic feedback"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad DragLock -bool false
defaults write com.apple.AppleMultitouchTrackpad DragLock -bool false
eok "Trackpad: disable DragLock"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Dragging -bool false
defaults write com.apple.AppleMultitouchTrackpad Dragging -bool false
eok "Trackpad: disable Dragging"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool false
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool false
eok "Trackpad: three finger drag"

defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
eok "Trackpad: enable tap to click for this user and for the login screen"

defaults write .GlobalPreferences com.apple.trackpad.scaling 2
eok "Trackpad: Faster pointer"

defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -int 1
defaults -currentHost write -g com.apple.trackpad.enableSecondaryClick -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 0
defaults write com.apple.AppleMultitouchTrackpad TrackpadCornerSecondaryClick -int 0
defaults -currentHost write -g com.apple.trackpad.trackpadCornerClickBehavior -int 0
eok "Map 'click or tap with two fingers' to the secondary click"

# --------------------------------------------------
ebox "SecOps"

eask "Enable FileVault"
sudo fdesetup enable || true
eok "Enable FileVault"

eok "Disable captive control"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

eask "Enable firewall"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on
eok "Enable firewall"

eask "Disable time machine"
sudo tmutil disable || true
eok "Disable time machine"

defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
eok "Prevent Time Machine from prompting to use new hard drives as backup volume"

defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
eok "Require password immediately after sleep or screen saver begins"

# --------------------------------------------------
ebox "Photos"

defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
eok "Prevent Photos from opening automatically when devices are plugged in"

# --------------------------------------------------
ebox "Screen"

sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true
eok "Enable HiDPI display modes (requires restart)"

sudo defaults write com.apple.universalaccess reduceMotion -bool true
eok "instead of sliding entire screen left/right, cross-fade... less jarring"

sudo defaults write com.apple.universalaccess reduceTransparency -bool true
eok "Make menubar always white (and turn off transparency everywhere)"

# --------------------------------------------------
ebox "Dock"

defaults write com.Apple.Dock showLaunchpadGestureEnabled -bool false
eok "Disable launchpad finger swipes"
defaults write com.Apple.Dock showAppExposeGestureEnabled -bool false
eok "Disable expose finger swipes"
defaults write com.Apple.Dock show-recents -bool false
eok "Don't show recently used applications in the Dock"

defaults write com.apple.dock magnification -int 1
defaults write com.apple.dock largesize -int 50
eok "Dock: magnify"

defaults write com.apple.dock persistent-apps -array
defaults write com.apple.dock persistent-others -array
eok "Dock: remove all app icons"

defaults write com.apple.dock showhidden -bool true
defaults write com.apple.dock tilesize -int 22
eok "Dock: hidden icons are transparent and small"

defaults write com.apple.dock orientation -string 'right'
eok "Dock: position right"

defaults write com.apple.dock show-process-indicators -bool FALSE
eok "Do not show app indicators in Dock"

# --------------------------------------------------
ebox "In's and Out's"

eok "Hammerspoon XDG Location"
defaults write org.hammerspoon.Hammerspoon MJConfigFile -string "~/.config/.hammerspoon/init.lua"

defaults write -g NSAutomaticCapitalizationEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticTextCompletionEnabled -bool false
eok "Disable autocorrect and key substitutions"

defaults write com.apple.ActivityMonitor ShowCategory -int 0
eok "Show all processes in Activity Monitor"

sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "I AM SERIOUS"
eok "Set login screen welcome text"

sudo defaults write /Library/Preferences/com.apple.alf allowdownloadsignedenabled -bool false || true
eok "Disable automatic signed software whitelisting"

sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool false || true
eok "Disable automatic software whitelisting"

sudo defaults write /Library/Preferences/com.apple.loginwindow DisableConsoleAccess -bool true
eok "Disable console logon from the logon screen"

sudo /usr/libexec/PlistBuddy -c "Set 'AC Power':'Display Sleep Timer' 5" /Library/Preferences/com.apple.PowerManagement.plist
eok "AC display sleep timer"

#sudo /usr/libexec/PlistBuddy -c "Set 'Battery Power':'Display Sleep Timer' 2" /Library/Preferences/com.apple.PowerManagement.plist
#eok "Battery display sleep timer"

defaults write com.apple.dock mru-spaces -bool false
eok "Don’t automatically rearrange Spaces based on most recent use"

defaults write com.apple.dock wvous-tl-corner -int 0
defaults write com.apple.dock wvous-tr-corner -int 0
defaults write com.apple.dock wvous-bl-corner -int 0
defaults write com.apple.dock wvous-br-corner -int 0
eok "Disable hot corners"

defaults write com.apple.dock expose-animation-duration -float 0.1
eok "Speed up Mission Control animations"

defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
eok "Save to disk (not to iCloud) by default"

defaults write com.apple.CrashReporter DialogType -string "none"
eok "Disable the crash reporter"

defaults write NSGlobalDomain AppleFontSmoothing -int 2
eok "Enable subpixel font rendering on non-Apple LCDs"

defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
eok "Avoid creating .DS_Store files on network or USB volumes"

sudo pmset -a sms 0
eok "Disable the sudden motion sensor as it’s not useful for SSDs"

defaults write com.apple.AdLib allowApplePersonalizedAdvertising -int 0
eok "advertising"

# --------------------------------------------------
ebox "Spotlight"

defaults write com.apple.spotlight orderedItems -array \
  '{"enabled" = 1;"name" = "APPLICATIONS";}' \
  '{"enabled" = 1;"name" = "MENU_EXPRESSION";}' \
  '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}' \
  '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
  '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
  '{"enabled" = 0;"name" = "SYSTEM_PREFS";}' \
  '{"enabled" = 0;"name" = "DOCUMENTS";}' \
  '{"enabled" = 0;"name" = "DIRECTORIES";}' \
  '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
  '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
  '{"enabled" = 0;"name" = "PDF";}' \
  '{"enabled" = 0;"name" = "MESSAGES";}' \
  '{"enabled" = 0;"name" = "CONTACT";}' \
  '{"enabled" = 0;"name" = "EVENT_TODO";}' \
  '{"enabled" = 0;"name" = "IMAGES";}' \
  '{"enabled" = 0;"name" = "BOOKMARKS";}' \
  '{"enabled" = 0;"name" = "MUSIC";}' \
  '{"enabled" = 0;"name" = "MOVIES";}' \
  '{"enabled" = 0;"name" = "FONTS";}' \
  '{"enabled" = 0;"name" = "MENU_OTHER";}'
eok "Disable spotlight bloat"

# Restart spotlight
# --------------------------------------------------
ebox "Finishup, cleanup and restart"

killall "SystemUIServer" > /dev/null 2>&1 || true
eok "kill: SystemUiServer"
killall "Finder" > /dev/null 2>&1 || true
eok "kill: Finder"
killall "Dock" > /dev/null 2>&1 || true
eok "kill: Dock"
killall mds > /dev/null 2>&1 || true
eok "kill: Spotlight"
# Make sure indexing is enabled for the main volume
sudo mdutil -i on / > /dev/null 2>&1 || true
eok "revive: Spotlight"
# Rebuild the index from scratch
sudo mdutil -E / > /dev/null 2>&1 || true
eok "Spotlight - reindex"

# Starting with Mac OS X Mavericks preferences are cached,
# so in order for things to get properly set using `PlistBuddy`,
# the `cfprefsd` process also needs to be killed.
#
# https://github.com/alrra/dotfiles/commit/035dda057ddc6013ba21db3d2c30eeb51ba8f200

killall "cfprefsd" > /dev/null 2>&1 || true
eok "kill: cached preferences"

ebox "You probably want to restart your machine now...."
eok "all done!"
