#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/_functions

if test ! "$(which brew)"; then
  sayok "brew not found, installing"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew update
else
  sayok "brew already installed"
fi
