#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/install-brew

statedir=$XDG_STATE_HOME/dotfiles
mkdir -p "$statedir"

ebox "Neovim setup"

einfo "Marksman"
json=$(curl -s https://api.github.com/repos/artempyanykh/marksman/releases | jq -r '.[0].assets[] | select(.name=="marksman-macos")')
id=$(echo "$json" | jq -r '.id')
if [ ! -f "$statedir"/marksman.version ] || [ "$(cat "$statedir"/marksman.version)" != "$id" ]; then
  echo "$id" > "$statedir"/marksman.version
  asset=$(echo "$json" | jq -r '.browser_download_url')
  curl -so /tmp/marksman -OL "$asset"
  mv /tmp/marksman ~/.local/bin/marksman
  chmod +x ~/.local/bin/marksman
  eok "Marksman"
else
  eok "Already at latest version"
fi

einfo "BASH support"
npm i -g bash-language-server
brew install shellharden shfmt
eok "BASH support added"

einfo "HTML support"
npm i -g vscode-langservers-extracted
eok "HTML support added"

einfo "RUST support"
brew install rustfmt rust-analyzer
eok "RUST support added"

einfo "MAKEFILE support"
brew install checkmake
eok "MAKEFILE support added"

#  js-beautify \
#  prettier \
#  pyright \
#  svelte-language-server \
#  typescript typescript-language-server \
#
#eok "pyright"
#eok "typescript typescript-language-server"
#eok "svelte-language-server"
#eok "vscode-langservers-extracted"
#eok "prettier"
#eok "js-beautify"
#
#cargo install stylua shellharden
#
#eok "stylua"
#eok "shellharden"
#
brew install lua-language-server
eok "lua-language-server"

ebox "Force plugins installation"
nvim +PackerSync
eok "PackerSync has run"
