#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/install-brew

ebox "Neovim setup"

#wget -O /tmp/marksman https://github.com/artempyanykh/marksman/releases/download/2022-06-23/marksman-macos
#mv /tmp/marksman ~/.local/bin/marksman
#chmod u+x ~/.local/bin/marksman
#eok "marksman"

einfo "BASH support"
pip install beautysh
npm i -g bash-language-server
brew install shellharden
eok "BASH support added"

#  js-beautify \
#  prettier \
#  pyright \
#  svelte-language-server \
#  typescript typescript-language-server \
#  vscode-langservers-extracted
#
#eok "pyright"
#eok "typescript typescript-language-server"
#eok "svelte-language-server"
#eok "vscode-langservers-extracted"
#eok "prettier"
#eok "js-beautify"
#
#cargo install stylua shellharden
#
#eok "stylua"
#eok "shellharden"
#
brew install lua-language-server
eok "lua-language-server"
#
#

ebox "Force plugins installation"
nvim +PackerSync +qall
eok "PackerSync has run"

ebox "Force install LspServers"
nvim +LspInstallServers
eok "PackeLspInstallServers has completed"
