#!/usr/bin/env bash

set -euo pipefail
. "$(dirname "$0")"/../stow/bin/.lib
. "$(dirname "$0")"/install-brew

ebox "Launching appliactions"

# todo: rethink the location of this configuration. Maybe in env?
bpshell=$(brew --prefix)/bin/bash
shells="/private/etc/shells"
# do not append if already added
if ! grep -qs "$bpshell" "$shells"; then
  eask "Changing bash to brew bash (v5)"
  echo "$(brew --prefix)"/bin/bash | sudo tee -a "$shells"
  chsh -s "$bpshell"
  sudo chsh -s "$bpshell"
  eok "We like Bash."
fi

[ "$(brew services info yabai 2> /dev/null)" = "" ] && brew services start yabai || brew services restart yabai
eok "started yabai"
[ "$(brew services info skhd 2> /dev/null)" = "" ] && brew services start skhd || brew services restart skhd
eok "started skhd"

cd /Applications
open -a Lulu.app
eok "started LuLu"

open -a itsycal.app
eok "started itsycal"

open -a xbar.app
eok "started xbar"
